### ISSUE TITLE
Create functionality of switching to particular tab when clicking on router-link

### ISSUE THREAD

**Issue by marichka-offen** [PrefectHQ/prefect-design#495]
As mentioned in [this issue](https://github.com/PrefectHQ/prefect/issues/7401), it would be helpful to be able to click on a router link and switch to a specific tab on the page. We have ability to redirect to different tab on the same page, but not when coming from different page

**Comment by pleek91** [comment]
This is possible at implementation using the selected v-model which can be bound to a param from the route using a composition like useRouteParam or useRouteQueryParam.

https://github.com/PrefectHQ/prefect-design/pull/419
