### ISSUE TITLE
Pmessage text hard to see when toggling light/dark mode

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect-design#932]
The PMessage component text is hard to see on certain modes with the new design updates. For example, when the warning boolean is enabled the light mode text looks great but the dark mode text is hard to read:

Light Mode Warning

![image](https://github.com/PrefectHQ/prefect-design/assets/104510333/dda5d846-d572-4a1d-ba82-631cd78569f6)

Dark Mode Warning

![image](https://github.com/PrefectHQ/prefect-design/assets/104510333/280b2357-67d1-4af6-9cae-7a07b345f9bf)

Another example with the success not showing in light mode vs. showing in dark mode

Success Light Mode:

![image](https://github.com/PrefectHQ/prefect-design/assets/104510333/569b7082-da1a-42c4-a777-4bd5b55e7ce8)

Success Dark Mode:

![image](https://github.com/PrefectHQ/prefect-design/assets/104510333/8df33e76-630f-47f6-b6a1-243f74dcdec6)

**Comment by brandonreid** [comment]
Thanks @robfreedy! I'll address this today.

**Comment by brandonreid** [comment]
This is deploying to staging now. @robfreedy if you could review and close this ticket if we're all good, I'd appreciate it! If there's still concern about contrast or anything else, please let me know.
